Repository anavatya/Chrome-Quotes, pull requests merged in 2023-10, with the labels that each got.

#5 Create a bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 Create issue template
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 added readme file for the quotes extension
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#17 Enhanced Quote button
  popup.html
Labels: hacktoberfest, hacktoberfest-accepted

#18 Changed color of Generate button as instructed
  popup.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 Update quote height
  popup.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#21 Added a new quote
  backgrounds/background6.jpg
  popup.js
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update background image
  popup.html
Labels: hacktoberfest, hacktoberfest-accepted
